package ember.ash.lastnightofdana.game;

public enum SceneEnum {
   MAIN_MENU,
   DANA_INTRO,
   DANA_TALKING_MAID,
   DANA_SEE_HAYMITCH,
   DANA_SALUTES_HAYMITCH,
   DANA_TALK_TO_HAYMITCH_1,
   DANA_WALK_WITH_HAYMITCH,
   DANA_AVOID_HAYMITCH,
   DANA_SLEEPING,
   DANA_GOES_TO_BED,
   DANA_GOES_TO_TOWN,
   DANA_GOES_TO_TOWN_TRANSITION,
   DANA_GOES_TO_TOWN_ENTRY,
}
